[package]
name = "no_default_features"
version = "0.1.0"
edition = "2021"

[dependencies]
glace = { path = "../../glace/glace", default-features = false }
helper_macros = { path = "../helper_macros" }
