[package]
name = "assist_proc_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
image = []
serde_json = []

[dependencies]
convert_case = "~0.6.0"
ignore = "~0.4.18"
proc-macro2 = "~1.0.46"
quote = "~1.0.21"
syn = { version = "~1.0.101", features = ["full"] }

