#!/usr/bin/env bash

set -eux

function testcrate() {
    local dir=$1
    (cd $dir && \
        cargo check && \
        cargo test && \
        cargo fmt -- --check && \
        cargo clippy -- -D clippy::all)
}

testcrate glace
(cd glace && cargo build)

readonly testcrates=$(ls -d test_suite/test_*)
for dir in $testcrates; do
    testcrate $dir
done
