#!/usr/bin/env bash

set -eux
set -o pipefail

function reformat() {
    local dir=$1
    (cd $dir && cargo fmt)
}

reformat glace

readonly testcrates=$(ls -d test_suite/test_*)
for dir in $testcrates; do
    reformat $dir
done
